export default {
    name:'contact',
    title:'Contact',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Name',
            type:'string',
            require:true 
        },
        {
            name:'email',
            title:'Email',
            type:'string',
            require:true 
        },
        {
            name:'message',
            title:'Message',
            type:'text',
            require:true 
        }
    ]
}